In [15]:
import pandas as pd
import numpy as np 
import tensorflow as tf
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Dense
from tensorflow import keras
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('diabetes_prediction_dataset.csv')

In [3]:
df

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0
...,...,...,...,...,...,...,...,...,...
99995,Female,80.0,0,0,No Info,27.32,6.2,90,0
99996,Female,2.0,0,0,No Info,17.37,6.5,100,0
99997,Male,66.0,0,0,former,27.83,5.7,155,0
99998,Female,24.0,0,0,never,35.42,4.0,100,0
99999,Female,57.0,0,0,current,22.43,6.6,90,0

In [4]:
# df.info

In [5]:
def one_hot_encode(df, columns):
    """ One-hot encode the categorical variables"""
    df = pd.get_dummies(df, columns, dtype=int)
    return df

df = one_hot_encode(df, columns=['gender', 'smoking_history'])

In [6]:
def scale_numeric_features(df, columns):
    """ Given the numeric features, apply standardscaler to them """
    scaler = StandardScaler()
    df[columns] = scaler.fit_transform(df[columns])
    return df

df = scale_numeric_features(df, columns=['age', 'hypertension', 'heart_disease', 'bmi', 'HbA1c_level', 'blood_glucose_level'])

In [7]:
# the data is ready to go, lets make our model

X = df.drop('diabetes', axis=1)
y = df['diabetes']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=69)

In [14]:
X.head()

,age,hypertension,heart_disease,bmi,HbA1c_level,blood_glucose_level,gender_Female,gender_Male,gender_Other,smoking_history_No Info,smoking_history_current,smoking_history_ever,smoking_history_former,smoking_history_never,smoking_history_not current
0,1.692704,-0.284439,4.936379,-0.321056,1.001706,0.047704,1,0,0,0,0,0,0,1,0
1,0.538006,-0.284439,-0.202578,-0.000116,1.001706,-1.426210,1,0,0,1,0,0,0,0,0
2,-0.616691,-0.284439,-0.202578,-0.000116,0.161108,0.489878,0,1,0,0,0,0,0,1,0
3,-0.261399,-0.284439,-0.202578,-0.583232,-0.492690,0.416183,1,0,0,0,1,0,0,0,0
4,1.515058,3.515687,4.936379,-1.081970,-0.679490,0.416183,0,1,0,0,1,0,0,0,0

In [18]:
# Create a sequential model
model = keras.Sequential([
    keras.layers.Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dense(1, activation='sigmoid')
])

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=100, batch_size=32, validation_split=0.2, verbose=0)

# Evaluate the model on the test set
loss, accuracy = model.evaluate(X_test, y_test)
print(f'Test loss: {loss}')
print(f'Test accuracy: {accuracy}')

782/782 [==============================] - 0s 288us/step - loss: 0.0824 - accuracy: 0.9717
Test loss: 0.08241836726665497
Test accuracy: 0.9716799855232239